# Generated by Django 5.1.6 on 2025-10-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='forwarded_gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gifts.gift'),
        ),
    ]
